export const OUTPUT_LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Portuguese",
  "Japanese",
  "Chinese (Simplified)",
  "Korean",
  "Italian",
  "Russian",
  "Arabic",
  "Hindi",
  "Dutch",
  "Turkish",
  "Polish",
];

export const CODE_FILE_EXTENSIONS: Record<string, string> = {
  ".js": "javascript",
  ".jsx": "javascript",
  ".ts": "typescript",
  ".tsx": "typescript",
  ".py": "python",
  ".java": "java",
  ".rs": "rust",
  ".go": "go",
  ".sql": "sql",
  ".sh": "bash",
  ".bash": "bash",
  ".json": "json",
  ".md": "markdown",
  ".txt": "text",
  ".rb": "ruby",
  ".php": "php",
  ".cs": "csharp",
  ".cpp": "cpp",
  ".c": "c",
};
